name: Deploy Express App to fpldict.zanaris.dev

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' 

      - name: Install dependencies
        run: npm install

      - name: Add Host Key 
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 65.109.8.91 >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: 65.109.8.91
          username: jason
          key: ${{ secrets.DEPLOY_USER_SSH_KEY }}
          port: 22
          script: |
            echo "Connection successful"
            echo "Deploying commit: $GITHUB_SHA"
            echo "Repository: $GITHUB_REPOSITORY"
            cd /home/dev/fpl_code_understat_dict
            git pull
            npm install
            # Check if fpl_code_understat_dict is running in PM2
            if pm2 list | grep -q "fpl_code_understat_dict"; then
              echo "fpl_code_understat_dict is already running, restarting..."
              pm2 restart fpl_code_understat_dict
            else
              echo "fpl_code_understat_dict is not running, starting..."
              pm2 start ecosystem.config.js
            fi

      # Add steps here to configure Nginx/Apache for subdomain deployment if needed
      # - Create/modify virtual host for fpl.zanaris.dev
      # - Point to the build output directory (if applicable)
      # - Reload/restart the web server